server:
  port : 8082

spring:
  application:
    name: Game Operations Service

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG